#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

sudo service nginx start
