#!/usr/bin/env bash
#Bash script for a clingy process
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM
echo '$$' > /var/run/myscript.pid
while true
do
	echo 'To infinity and beyond'
done
