#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
while read -r line
do
	IFS=':' read -r -a cut_array <<< "$line"
	echo "The user ${cut_array[0]} is part of the ${cut_array[3]} gang, lives in ${cut_array[5]} and rides ${cut_array[6]}. ${cut_array[2]}'s place is protected by the passcode ${cut_array[1]}, more info about the user here: ${cut_array[4]}"
done < "/etc/passwd"
