#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user

sed -i '1s/^/user nginx;\n/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
service nginx restart
