#!/usr/bin/env bash

apt-get update
apt-get install -y apache2

sed -i "s/80/8080/g" /etc/apache2/sites-available/000-default.conf
sed -i "s/80/8080/g" /etc/apache2/ports.conf
service apache2 restart
rm -r /var/run/apache2/apache2.pid

sudo useradd nginx
sudo passwd -d nginx

apt-get install -y nginx
sed -i '1s/^/# /' /etc/nginx/nginx.conf
service nginx restart
