#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.210.89.176
    HostName 54.210.89.176
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
